access-token:
  private: "access-refresh-token-keys/access-token-private.key"
  public: "access-refresh-token-keys/access-token-public.key"
refresh-token:
  private: "access-refresh-token-keys/refresh-token-private.key"
  public: "access-refresh-token-keys/refresh-token-public.key"
spring:
  data:
    mongodb:
      uri: mongodb+srv://root:root@cluster0.1mqpgq0.mongodb.net/gym?retryWrites=true&w=majority&appName=Cluster0
logging:
  level:
    org.springframework.security: DEBUG